name: Style Check

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'oracle'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Change to java directory
        run: cd java
        
      - name: Run Checkstyle
        run: |
          cd java
          mvn checkstyle:check
